# Generated by Django 4.0.3 on 2022-05-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpgsapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
    ]
